# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment_tonight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_location', models.CharField(max_length=200)),
                ('event_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='cities',
            name='town_picture',
        ),
    ]
