# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment_tonight', '0002_auto_20170321_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='upload_photo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
