# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment_tonight', '0005_auto_20170411_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='upload_photo',
            field=models.FileField(upload_to=b'media'),
        ),
    ]
