# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment_tonight', '0012_auto_20170412_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
