# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment_tonight', '0015_auto_20170420_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(verbose_name=b'Event date:'),
        ),
    ]
