# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment_tonight', '0017_auto_20170420_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
    ]
