# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 08:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment_tonight', '0019_event_event_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
